### ISSUE TITLE
Issue with AJAX

### ISSUE THREAD

**Issue by sabeti05** [jerrylow/basictable#12]
I am trying this code, But it seems it is not working for the tables loaded with AJAX:

```
$(document).on('ready ajaxSuccess', function() {
	$('table').basictable({
		forceResponsive: false
	});
});
```

**Comment by jerrylow** [comment]
@sabeti05 just created a quick fiddle to test this and not getting any problem https://jsfiddle.net/pr175wq6/1/

Do you have anymore information/errors you're getting?
