### ISSUE TITLE
Demo page - tableWrapper should be corrected to tableWrap

### ISSUE THREAD

**Issue by crispyteeth** [jerrylow/basictable#13]
![image](https://user-images.githubusercontent.com/38844809/92518261-0a8ce780-f1e6-11ea-9e86-1e9f28466a72.png)

In the demo should the property be _tableWrap_ instead of _tableWrapper_?

Thanks.

**Comment by jerrylow** [comment]
Thanks fixed: https://github.com/jerrylow/basictable/commit/96be57ae2c2d9af2f1ccad7bf5f39206e8a2b51a
