### ISSUE TITLE
feature_request(dependencies): vanilla JavaScript or Cash instead of JQuery

### ISSUE THREAD

**Issue by Kristinita** [jerrylow/basictable#14]
### 1. Summary

It would be nice, if would be possible to use Basic Table without JQuery.

1. Possible it would be nice to have Basic Table written in a pure JS.
1. Or make the plugin Cash-compatible.

#### 2.1. Common cause

JQuery size, web performance.

#### 2.2. Details

JQuery is a large library that can decrease a web performance. For example, see the article “[**You might not need jQuery: A 2018 Performance case study**](https://medium.com/@trombino.marco/you-might-not-need-jquery-a-2018-performance-case-study-aa6531d0b0c3)”. I don’t use JQuery on my site, and I don’t think having as much dependency as JQuery solely for responsive tables is the best solution.

#### 3.1. Shortly

From [**Cash GitHub Readme**](https://github.com/fabiospampinato/cash#cash):

> Cash is an absurdly small jQuery alternative for modern browsers (IE11+) that provides jQuery-style syntax for manipulating the DOM.

#### 3.2. Details

I copied it from [**cash GitHub Readme**](https://github.com/fabiospampinato/cash#comparison):

| Size               | Cash        | Zepto 1.2.0 | jQuery Slim 3.4.1 |
| ------------------ | ----------- | ----------- | ----------------- |
| Unminified         | **36.5 KB** | 58.7 KB     | 227 KB            |
| Minified           | **16 KB**   | 26 KB       | 71 KB             |
| Minified & Gzipped | **6 KB**    | 9.8 KB      | 24.4 KB           |

A **76.6%** gain in size reduction compared to jQuery. If you need a smaller bundle, we support [**partial builds**](https://github.com/fabiospampinato/cash/blob/master/docs/partial_builds.md) too.

| Features                 | Cash                               | Zepto 1.2.0                    | jQuery Slim 3.4.1              |
| ------------------------ | ---------------------------------- | ------------------------------ | ------------------------------ |
| Supports Older Browsers  | ❌                                  | ❌                             | ✔                              |
| Supports Modern Browsers | ✔                                  | ✔                             | ✔                              |
| Actively Maintained      | ✔                                  | ❌                             | ✔                              |
| Namespaced Events        | ✔                                  | ❌                             | ✔                              |
| Typed Codebase           | ✔ (TypeScript)                     | ❌                             | ❌                              |
| TypeScript Types         | ✔ (generated from code)            | ⚠️ (via DefinitelyTyped)       | ⚠️ (via DefinitelyTyped)        |
| Partial Builds           | ✔ (can exclude individual methods) | ⚠️ (can exclude whole modules) | ⚠️ (can exclude whole modules)  |

### 4. Additional links

1. [**Cash documentation**](https://kenwheeler.github.io/cash/#docs)
1. [**Migration from jQuery to Cash guide**](https://github.com/fabiospampinato/cash/blob/master/docs/migration_guide.md)

Thanks.

**Comment by jerrylow** [comment]
Thanks, a vanilla JS version is in the works.

**Comment by jerrylow** [comment]
Thanks for the issue - reminded me to finish it up. I've pushed a `2.0.0` version adding the vanilla JS version https://github.com/jerrylow/basictable/releases/tag/v2.0.0.

**Comment by Kristinita** [comment]
**Status: DONE** :heavy_check_mark:

Vanilla JS version of Basic Table works for me.

Thanks!
