### ISSUE TITLE
table cell widths are kept

### ISSUE THREAD

**Issue by Vertigrator** [jerrylow/basictable#16]
If a table has cell widths, say a ten column table has width on each cell of 10%, then this is still kept on the TD that is in the new table that Basictable creates. So this means that the content width is tiny with heaps of white space to the right of it. It would be best if Basictable could remove the width. It is also adding width: 6.5em which is messing with the display. If that is removed then it displays nicely.

**Comment by jerrylow** [comment]
@Vertigrator are the widths set inline or via CSS? If it's set with CSS you could override with your own CSS (which could work with inline too with `!important`. Alternatively I could add some events so users can create their own callback to do this.

**Comment by Vertigrator** [comment]
The widths were inline, added by SharePoint automatically. So what I did was use javascript to remove all the width attributes after the page loads. I hate rich text editors that try to be smart by adding things like this that we don't want.
`// Remove all the width attributes that SharePoint adds to tables
$(document).ready(function ($) {
    $('.epa .main-content table th, .epa .main-content table td').each(function () {
        $(this).removeAttr("width");
    });
});`

**Comment by jerrylow** [comment]
Ah I see, yes if you have no control over that - unfortunately. BTW based on your sample from the other issue it looks like the widths are set in the style attribute rather than the width attribute. You also don't have to do a `.each` for jQuery as it'll apply to all instances (not vanilla js though) so you could just do:

```
$('.epa .main-content table th, .epa .main-content table td').css('width', '');
```

**Comment by Vertigrator** [comment]
Brilliant. Thanks for the help. :-)
