### ISSUE TITLE
Multiple span.bt-content inside td

### ISSUE THREAD

**Issue by zoxon** [jerrylow/basictable#2]
Plugin create a lot of `span.bt-content` inside `td`.
http://codepen.io/Zoxon/pen/JGEvQQ

![2016-01-04 16-14-42](https://cloud.githubusercontent.com/assets/3866196/12087585/5caeb2f4-b2fe-11e5-9212-2bc6a62cc374.png)

**Comment by zoxon** [comment]
@falconx Tnak you

**Comment by jerrylow** [comment]
@zoxon besides that I noticed there were no support for `<tfoot>`. I've added a fix.

**Comment by zoxon** [comment]
@jerrylow thankyou, anyway I'm create my own fork. Maybe you will find something interesting there https://github.com/zoxon/basictable
I do not create pull request because there are a lot of changes
