### ISSUE TITLE
feature_request(thead): support tables without thead

### ISSUE THREAD

**Issue by Kristinita** [jerrylow/basictable#25]
### 1. Summary

It would be nice, if Basic Table will support tables without `<thead>` tag.

### 2. Validity of tables without thead

1. According to HTML Living Standard as of 15.8.2022, `<thead>` tag is [**optional**](https://html.spec.whatwg.org/multipage/tables.html#the-table-element), not required for tables.
1. Official W3C HTML validator and another validators — htmllint, htmlhint, linthtml — allow the use of tables without `<thead>`.

#### 3.1. Sources

[**Sources on Repl.it**](https://replit.com/@Kristinita/KiraBasicTable-without-thead):

1. `index.html`

	```html
	<!DOCTYPE html>
	<html>

	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Kira Basic Table without thead</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/basictable/dist/css/basictable.min.css">
		<script src="https://cdn.jsdelivr.net/npm/basictable/dist/js/basictable.min.js" defer></script>
		<script src="basictable.js" defer></script>
	</head>

	<body>
		<table>
			<tbody>
				<tr>
					<td>Kira Amazing</td>
					<td>Kira Genius</td>
					<td>Kira Goddess</td>
				</tr>
			</tbody>
		</table>
	</body>

	</html>

	```

1. `basictable.js`

	```javascript
	new basictable('table');
	```

#### 3.2. Desired behavior

Stack the table as for tables with `<thead>`.

#### 3.3. Current behavior

[**Demonstration on Repl.it**](https://kirabasictable-without-thead.kristinita.repl.co/).

Error in browser console:

```js
Uncaught DOMException: Element.querySelectorAll: 'tr:first td' is not a valid selector basictable.min.js:4
   _setup https://cdn.jsdelivr.net/npm/basictable/dist/js/basictable.min.js:4
   forEach self-hosted:164
   _setup https://cdn.jsdelivr.net/npm/basictable/dist/js/basictable.min.js:4
   basictable https://cdn.jsdelivr.net/npm/basictable/dist/js/basictable.min.js:4
   <anonymous> https://kirabasictable-without-thead.kristinita.repl.co/basictable.js:1
```

![Basic Table without thead error](https://i.imgur.com/2JVZAQ1.png)

#### 3.4. Behavior with thead

If I add `<thead>` syntax to this table ([**sources on Repl.it**](https://replit.com/@Kristinita/KiraBasicTable-with-thead)):

```diff
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
-	<title>Kira Basic Table without thead</title>
+	<title>Kira Basic Table with thead</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/basictable/dist/css/basictable.min.css">
	<script src="https://cdn.jsdelivr.net/npm/basictable/dist/js/basictable.min.js" defer></script>
	<script src="basictable.js" defer></script>
</head>

<body>
+ 	<thead>
+		<tr>
+			<th>One</th>
+			<th>Two</th>
+			<th>Three</th>
+		</tr>
+	</thead>
	<table>
		<tbody>
			<tr>
				<td>Kira Amazing</td>
				<td>Kira Genius</td>
				<td>Kira Goddess</td>
			</tr>
		</tbody>
	</table>
</body>

</html>

```

Basic Table will successfully work, see [**Repl.it demonstration**](https://kirabasictable-with-thead.kristinita.repl.co/).

Thanks.

**Comment by jerrylow** [comment]
Thanks for catching that, updated https://github.com/jerrylow/basictable/releases/tag/v2.0.3
