### ISSUE TITLE
Move no necessary dependencies to devDependencies

### ISSUE THREAD

**Issue by pakmanlh** [jerrylow/basictable#37]
Hi there! 
I struggled to add BasicTable to a major project managed by Composer due the package.json has some libraries dependencies used only for the development or during the building process.
It would be nice to moved them from `dependencies` to `devDependencies` so the library can be included having only the libraries really needed.
Thanks!

**Comment by jerrylow** [comment]
I was actually just thinking the same thing couple months ago but completely forgot, will update.

**Comment by jerrylow** [comment]
Moved in 2.0.5
