### ISSUE TITLE
Multiple tables

### ISSUE THREAD

**Issue by hankszeto** [jerrylow/basictable#4]
Hi Jerry,

Thanks for the great jQuery plugin. It works great with a single table. However, if I have more than one table on the page, selected using the 'table' element, the headings from the first table are being used on the second and third tables.

I'm calling basictable like this:

$('table').basictable({
breakpoint: 768,
});

Thanks.

**Comment by jerrylow** [comment]
Hey @hankszeto, thanks for finding that, going to push a fix for that.

**Comment by hankszeto** [comment]
Thanks @jerrylow. Tested and it is working great! :)
