### ISSUE TITLE
problem with datatable.

### ISSUE THREAD

**Issue by aliqasemzadeh** [jerrylow/basictable#8]
I found this plugin is very useful.
But when I use it in datatable it with miss thead data after search data.
![12](https://user-images.githubusercontent.com/26847446/38181290-539df89a-3647-11e8-9bd3-efa6083bdee1.png)

**Comment by jerrylow** [comment]
Hey, @AGhasemzadeh do you mean this plugin https://datatables.net/, or are you referring to your own data table? What does the DOM and CSS look like?
