### ISSUE TITLE
Issue with dynamic table

### ISSUE THREAD

**Issue by joko13** [jerrylow/basictable#9]
When a new table row gets added dynamically via AJAX/KnockoutJS, the table headers of the new row are blank in responsive mode. I tried basictable('destroy') and running basictable again after the new row gets added dynamically, but the table headers dont show up in responsive mode.

**Comment by jerrylow** [comment]
@joko13 did you select the table and initiate `start` after the ajax table was generated?

**Comment by MahmoudH96** [comment]
Yes I did but the same result, I tried to destroy it and then recreate the table, besides trying to stop and start it but I still got the same results, the new dynamic row does not contain
any headers like the following image:
![issue](https://user-images.githubusercontent.com/14193071/54201075-78fbc700-44d5-11e9-8afa-04e230277c05.PNG)

**Comment by jerrylow** [comment]
@MahmoudH96 did you do a `destroy` then `start`?

```
$('table').basictable('destroy');
$('table').basictable('start');
```

https://jsfiddle.net/0daoebzf/1/

**Comment by jerrylow** [comment]
@MahmoudH96 I just added a `restart` method so you don't have to redefine the table settings again, https://github.com/jerrylow/basictable#restart

**Comment by MahmoudH96** [comment]
I will try it, thanks
